# Generated by Django 4.1.2 on 2022-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('order_id', models.TextField()),
                ('container', models.TextField()),
                ('date_work', models.TextField(default='')),
                ('time_in', models.TextField()),
                ('time_out', models.TextField()),
                ('w1_start', models.TextField()),
                ('w2_start', models.TextField()),
                ('w3_start', models.TextField()),
                ('w4_start', models.TextField()),
                ('w5_start', models.TextField()),
                ('w1_stop', models.TextField()),
                ('w2_stop', models.TextField()),
                ('w3_stop', models.TextField()),
                ('w4_stop', models.TextField()),
                ('w5_stop', models.TextField()),
                ('w1_break_on', models.TextField()),
                ('w1_break_off', models.TextField()),
                ('w2_break_on', models.TextField()),
                ('w2_break_off', models.TextField()),
                ('w3_break_on', models.TextField()),
                ('w3_break_off', models.TextField()),
                ('w4_break_on', models.TextField()),
                ('w4_break_off', models.TextField()),
                ('w5_break_on', models.TextField()),
                ('w5_break_off', models.TextField()),
                ('supervisor', models.TextField()),
                ('customer', models.TextField()),
                ('product', models.TextField()),
                ('packages', models.TextField()),
                ('sku', models.TextField()),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('container', models.TextField()),
                ('unload_time', models.TextField()),
                ('workers', models.TextField()),
                ('w1', models.TextField()),
                ('w2', models.TextField()),
                ('w3', models.TextField()),
                ('w4', models.TextField()),
                ('w5', models.TextField()),
                ('tw', models.TextField()),
                ('br1', models.TextField()),
                ('br2', models.TextField()),
                ('br3', models.TextField()),
                ('br4', models.TextField()),
                ('br5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
    ]
